### ISSUE TITLE
Update to support newer version of Ulauncher

### ISSUE THREAD

**Issue by Hedronmx** [friday/ulauncher-clipboard#10]
Please make this usable on newer versions of Ulauncher

**Comment by friday** [comment]
Ulauncher 5 isn't released yet. Once there are dev builds for Arch I'll fix the compat, but until then it's too cumbersome to switch back and forth on my distro.

See https://github.com/friday/ulauncher-hash2/issues/2

**Comment by Hedronmx** [comment]
I see! No problem. Sorry to bother

**Comment by friday** [comment]
No worries!

**Comment by materemias** [comment]
@friday could you please update according to [Ulauncher/Ulauncher#385](https://github.com/Ulauncher/Ulauncher/issues/385#issuecomment-502311631)

**Comment by friday** [comment]
Done. Have tested all clients, but might have missed something. Create a new issue in that case
