### ISSUE TITLE
Copied text not accessible

### ISSUE THREAD

**Issue by ibot3** [friday/ulauncher-clipboard#11]
I noticed a strange behavior when using this extension. As soon as I select something from the clipboard history and trying to paste it, the application in which I  try to paste does not respond anymore.

The command `xclip -selection c -o` does not terminate when calling it which probably causes the non responding application. This command does usually return the current clipboard content. But it runs forever, if I selected something from the clipboard history before.

I am using arch and experienced the same problem with CopyQ and GPaste.

When using xclip with verbose output I get the following log:

> Connected to X server.
Using selection: XA_CLIPBOARD
Using UTF8_STRING.
...

**Comment by friday** [comment]
Which DE? X11 or Wayland? Which Ulauncher version? I'm also using Arch, and it works for me. It's using the same method as Ulauncher for copying text, so it should work.

This is where it's defined: https://github.com/friday/ulauncher-clipboard/blob/c3141d4606d7a2dbe12e0bb085489ad3c062beb5/lib.py#L42

**Comment by ibot3** [comment]
I am Using X11 with i3wm and Ulauncher version 5.3.0~beta1. Maybe it is because of the beta. However, the clipboard works fine with other extensions.

**Comment by friday** [comment]
I'm not using the beta but I tested it when migrating the extension, and it definitely worked.

Since I can't really replicate the issue or have the time to try right now I'll leave the issue open. If you have the time and skills you can try manually "copying" with the code I linked to, and see if that's the problem. If not there might be something I can do.

Also run Ulauncher with `ulauncher -v` to see a detailed log if some error in my code is triggered.

**Comment by ibot3** [comment]
I came to the conclusion that the problem is the usage of the GTK clipboard functions. I used the `set_text()` and `store()` methods independent of this extension and had the same problem. So this isn't a problem specific to this extension. However, I have no idea yet why this occurs.

**Comment by jurgel** [comment]
I had exactly the same problem as yours. It seems it's because of how X11 handles the clipboard. I fixed it and make a pull request here #14

**Comment by friday** [comment]
Based on [this comment](https://github.com/friday/ulauncher-clipboard/issues/11#issuecomment-524667844) I'm not sure #14 fixed the issue for the reporter, but  9ac2695e0e59b17fea98959d1e66303c913c7734 should have (not implemented for CopyQ yet).

I'm closing, assuming it's fixed. If this still happens to someone please comment here or create a new issue.
