### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by jrseliga** [friday/ulauncher-clipboard#12]
Ulauncher: 5.4.0
Distribution: Ubuntu 19.04
Desktop Environment: Gnome 3.32.2
Display Server: Both Wayland and X11
Clipboard Manager: GPaste

Launching the clipboard extension with `c` and following it with a `space` does successfully retrieve the clipboard history, however when typing a search only the loading indicator is displayed:

![Screenshot from 2019-11-05 22-35-32](https://user-images.githubusercontent.com/3277067/68266273-9bba8d00-001c-11ea-8190-ae98fa77d4dd.png)

**Comment by friday** [comment]
Thank you for the report.

If you update the extension through Ulaunchers preferences it should work now.
