### ISSUE TITLE
Error after recent update, looking for incorrect clipboard manager

### ISSUE THREAD

**Issue by jrseliga** [friday/ulauncher-clipboard#13]
@friday after updating the extensions based on the recommendation of this https://github.com/friday/ulauncher-clipboard/issues/12 a new error has come where it seems the extension is looking for the incorrect clipboard manager.

![image](https://user-images.githubusercontent.com/3277067/69016020-5aa17180-0968-11ea-9338-c37989bac887.png)

Unfortunately that's the best screenshot I can grab from the pop-up, but these are my settings:

![image](https://user-images.githubusercontent.com/3277067/69016038-815fa800-0968-11ea-93a5-d14c66139244.png)

**Comment by friday** [comment]
Sorry for the late reply again @jrseliga. I don't think this is a ulauncher-clipboard error though. I don't listen to copyq's `onClipboardChanged` event.

I'm guessing you installed and uninstalled copyq, and still have some startup script or desktop entry remaining. Maybe run Gnome Tweaks and check the "Startup Applications" there?

Does the extension work for you with GPaste otherwise?

**Comment by beskhu3epnm** [comment]
This issue still persists. After updating from v4 to v5, it does not recognize anything in the clipboard. It continuously says 'Loading'. I don't see any option to change any settings, like selecting another clipboard manager.

**Comment by friday** [comment]
It works fine in v5 @beskhu3epnm. I use it every day now. Please close Ulauncher and restart it with the command `ulauncher -v` and create a new issue where you post the output. You will likely have an error somewhere.

![ulauncher-clipboard](https://user-images.githubusercontent.com/515120/71427060-e3bc6e80-26b3-11ea-9728-27fda739f656.png)

**Comment by beskhu3epnm** [comment]
The problem remains of course. Here is the verbose output - [https://files.catbox.moe/j9n6ck.txt](https://files.catbox.moe/j9n6ck.txt)

```
com.github.friday.ulauncher-clipboard | 2019-12-25 00:36:57,693 | INFO | ulauncher-clipboard: ensureStatus() | Attempting to start manager Clipster
ERROR:Daemon already running: pid 3415
com.github.friday.ulauncher-clipboard | 2019-12-25 00:36:58,522 | INFO | ulauncher-clipboard: ensureStatus() | Attempting to start manager Clipster
ERROR:Daemon already running: pid 3415
com.github.friday.ulauncher-clipboard | 2019-12-25 00:36:59,396 | INFO | ulauncher-clipboard: ensureStatus() | Attempting to start manager Clipster
ERROR:Daemon already running: pid 3415
com.github.friday.ulauncher-clipboard | 2019-12-25 00:37:00,322 | INFO | ulauncher-clipboard: ensureStatus() | Attempting to start manager Clipster
ERROR:Daemon already running: pid 3415
```

**Comment by friday** [comment]
@beskhu3epnm I think I fixed it.

**Comment by beskhu3epnm** [comment]
Thanks, working now.

**Comment by friday** [comment]
I managed to reproduce this error now, by uninstalling copyq while it's still running. It's completely unrelated to this extension.

**Comment by beskhu3epnm** [comment]
I made a fresh install of Linux Mint 20, using the most recent stable version of Ulauncher (v5.8.0), with the Clipboard extension installed. But using 'c', it's endlessly searching for my clipboard history. I can't seem to get it to work. Not sure what to do, it's on 'Auto' mode.

**Comment by friday** [comment]
Thanks for updating the comment @beskhu3epnm :). Sorry I haven't been able to keep up.
