### ISSUE TITLE
Does not show copied images

### ISSUE THREAD

**Issue by KorbsStudio** [friday/ulauncher-clipboard#18]
When copying an image, images do not show up on ULauncher.
I use CopyQ and it does have the ability to remember what images I copied.

**Comment by friday** [comment]
Yes. It was designed for text, and I never even tested it with images. It's not currently supported to embed images in Ulauncher the small icon, and it's not a use case I need.

Images aren't really searchable/filterable the same way either.

If you the clipboard primarily for text, then maybe you can use CopyQ's own UI directly for these time this isn't enough?
