### ISSUE TITLE
Feature: Avoid running clipster daemon when CopyQ or GPaste selected

### ISSUE THREAD

**Issue by chessmango** [friday/ulauncher-clipboard#19]
Not sure how easy this would be to implement, but just quality-of-life wise it'd be nice to drop the `clipster_bin` daemon if/when another source is used to conserve memory

**Comment by friday** [comment]
ulauncher-clipboard checks if you have picked any specific clipboard manager. If not it tries to find if you have any running. If not it checked if you have any installed. If neither of those are true it downloads a local copy of clipster, starts it and uses that.

So if you're concerned about memory usage it should be very easy to avoid this issue. Just kill the process manually, reboot or (assuming you would know this before installing the extension) make sure you have the clipboard manager of your choice installed before installing the extension.

If this isn't the case there's a bug somewhere, and I will look at it.

I agree it would be nice if ulauncher-clipboard handled this, but not sure the pros outweigh the cons (increasing the complexity). It's not just clipster. It starts any of them if they're the selected manager and not already running. So if you're changing the settings a lot this would happen, but I think this is the kind of thing people set and forget.

**Comment by chessmango** [comment]
Cool, understandable. I've found that the process is started again regardless of setting, though this was after initially having no external manager. I guess might be worthwhile to check up on that? But considering minimal memory use anyway, no biggie :smile:

**Comment by friday** [comment]
I'll look into it when I have time. Thanks for the report :+1:

**Comment by friday** [comment]
This is not happening if you start ulauncher with a supported clipboard manager installed.
