### ISSUE TITLE
Clearing the clipboard history

### ISSUE THREAD

**Issue by ivanmood0** [friday/ulauncher-clipboard#22]
There was a problem clearing the clipboard history. Since I use the auto setting and the standard clipboard manager as far as I understand it is 'Clipster', how do I clear the history? The 'Clipster' package is not installed in the system (and I also do not want to install it, I use the gnome extension for the buffer) so the keys for cleaning type '--erase-entire-board' do not work. I see Clipster is in the folder with the extension Ulauncher, but where the file with the saved history contains I do not know.

**Comment by friday** [comment]
I don't support that feature. You can install clipster and run the command to erase it, then uninstall. Or you can delete, ~/.local/share/clipster/history or set up clipster config to flush it regularly https://github.com/mrichar1/clipster#config-file.

Maybe a future version of ulauncher-clipboard will, but I don't aim to support all clipboard manager features. This extension is just for integrating the most convenient clipboard history functionality with Ulauncher.

**Comment by ivanmood0** [comment]
> I don't support that feature. You can install clipster and run the command to erase it, then uninstall. Or you can delete, ~/.local/share/clipster/history or set up clipster config to flush it regularly https://github.com/mrichar1/clipster#config-file.
> 
> Maybe a future version of ulauncher-clipboard will, but I don't aim to support all clipboard manager features. This extension is just for integrating the most convenient clipboard history functionality with Ulauncher.

It is clear, but cleaning or deleting the history file, for some reason does not clear the history. Let's just move past this area. Are you planning to support the 'Clipboard Indicator' gnome extension as a clipboard manager?

**Comment by friday** [comment]
I don't plan to add support for anything. Just fixing bugs if reported. If people want to submit pull requests for new managers I will accept them though.
