### ISSUE TITLE
Pasteboard issue with Ulauncher, CopyQ, ulauncher-clipboard and ulauncher-two-factor-authenticator

### ISSUE THREAD

**Issue by art-lucas** [friday/ulauncher-clipboard#40]
I'm not sure this is the right place to report this issue.
I'm using Ubuntu 22.04 with `Ulauncher` and `CopyQ` as well as `ulauncher-clipboard`. I've also installed and activated the Ulauncher extension two-factor-authenticator (https://github.com/endorama/ulauncher-two-factor-authenticator), which is now working well.
CopyQ works as intended, and so does `ulauncher-clipboard`.
However, after launching Ulauncher, activating two-factor-authenticator (keyword: `2fa`), and hitting `Enter` or `Alt+1` to select the first entry, there's nothing in the clipboard, i.e., `CopyQ`/ `ulauncher-clipboard`.
Any idea how to fix/debug this will be much appreciated.

**Comment by friday** [comment]
That's an issue with the main dependency of the other extension.
