### ISSUE TITLE
Copying items doesn't work

### ISSUE THREAD

**Issue by mkalitka** [friday/ulauncher-clipboard#41]
Items aren't copied after clicking them. I'm using:

- Python 3.11 (probably the cause)
- Ulauncher v6 dev
- Wayland (Hyprland)
- Clipman as my clipboard manager

The plugin shows all copied items, but selecting and clicking them doesn't copy them to the clipboard.

My solution for now is to checkout to this [commit](https://github.com/friday/ulauncher-clipboard/commit/107c920ddf4be4303821d1ef3a234aba8e6aa419).

Ulauncher debug logs don't contain any errors.

**Comment by friday** [comment]
Thanks for reporting. I think the latest commit should fix it?

**Comment by friday** [comment]
I have made more changes now. I installed and verified all the other managers and tried to set up Clipman in Gnome Wayland, but I couldn't get it to work, so need help verifying.
